# -*- coding: utf-8 -*-
"""
    File name: testcases.py
    Author: Harishankar Chinnathambi
    Created on: Sun Mar 12 15:36:17 2017
    Python Version:2.7.12
"""
import MLDateTime as dt


print dt.parse("now")
print dt.parse("today")
print dt.parse("eod")
print dt.parse("tomorrow")
print dt.parse("day after tomorrow")
print dt.parse("day before yesterday")
print dt.parse("eom")
print dt.parse("next few days")
print dt.parse("next month")
print dt.parse("next year")
print dt.parse("last month")
print dt.parse("last year")
print dt.parse("this year")
print dt.parse("first quarter")
print dt.parse("second quarter")
print dt.parse("third quarter")
print dt.parse("fourth quarter")
print dt.parse("a week ago")
print dt.parse("one week ago")
print dt.parse("current week")
print dt.parse("coming week")
print dt.parse("last week")
print dt.parse("next week")
print dt.parse("noon")
print dt.parse("midday")
print dt.parse("in a couple of hours")
print dt.parse("in few hours")
print dt.parse("half an hour")
print dt.parse("in about half an hour")
print dt.parse("morning")
print dt.parse("evening")
print dt.parse("lunch")
print dt.parse("night")
print dt.parse("in 24 hours")
print dt.parse("in 24 hrs")
print dt.parse("after lunch")
print dt.parse("in one hour")
print dt.parse("in an hour")
print dt.parse("15 minutes from now")
print dt.parse("in 1 hour")
print dt.parse("harish")
print dt.parse("1 am")
print dt.parse("2 am")
print dt.parse("3 am")
print dt.parse("4 am")
print dt.parse("5 am")
print dt.parse("6 am")
print dt.parse("7 am")
print dt.parse("8 am")
print dt.parse("9 am")
print dt.parse("10 am")
print dt.parse("11 am")
print dt.parse("12 am")
print dt.parse("1 pm")
print dt.parse("2 pm")
print dt.parse("3 pm")
print dt.parse("4 pm")
print dt.parse("5 pm")
print dt.parse("6 pm")
print dt.parse("7 pm")
print dt.parse("8 pm")
print dt.parse("9 pm")
print dt.parse("10 pm")
print dt.parse("11 pm")
print dt.parse("12 pm")
print dt.parse("sunday")
print dt.parse("monday")
print dt.parse("tuesday")
print dt.parse("wednesday")
print dt.parse("thursday")
print dt.parse("friday")
print dt.parse("saturday")
print dt.parse("XXX")
print dt.parse("january")
print dt.parse("february")
print dt.parse("march")
print dt.parse("april")
print dt.parse("may")
print dt.parse("june")
print dt.parse("july")
print dt.parse("august")
print dt.parse("september")
print dt.parse("october")
print dt.parse("november")
print dt.parse("december")
print dt.parse("TOMORROW")
print dt.parse('1 o\'clock')
print dt.parse('2 o\'clock')
print dt.parse('3 o\'clock')
print dt.parse('4 o\'clock')
print dt.parse('1 o\'clock')
print dt.parse('5 o\'clock')
print dt.parse('6 o\'clock')
print dt.parse('7 o\'clock')
print dt.parse('8 o\'clock')
print dt.parse('9 o\'clock')
print dt.parse('10 o\'clock')
print dt.parse('11 o\'clock')
print dt.parse('12 o\'clock')